-- public.qna definition

-- Drop table

-- DROP TABLE public.qna;

CREATE TABLE public.qna (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_id varchar(100) NULL,
	updated_at timestamp(6) NOT NULL,
	updated_id varchar(100) NULL,
	answer_content text NULL,
	answered_at timestamp(6) NULL,
	answerer_emp_no varchar(100) NULL,
	category varchar(50) NULL,
	"content" text NULL,
	is_public bool NOT NULL,
	questioner_emp_no varchar(100) NOT NULL,
	status varchar(20) NOT NULL,
	title varchar(500) NOT NULL,
	view_count int4 NOT NULL,
	CONSTRAINT qna_pkey PRIMARY KEY (id),
	CONSTRAINT qna_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ANSWERED'::character varying, 'CLOSED'::character varying])::text[])))
);