-- public.qna_attachments definition

-- Drop table

-- DROP TABLE public.qna_attachments;

CREATE TABLE public.qna_attachments (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- 첨부파일ID
	content_type varchar(100) NULL, -- 콘텐츠타입
	created_at timestamp(6) NOT NULL, -- 생성일시
	file_path varchar(500) NOT NULL, -- 파일경로
	file_size int8 NOT NULL, -- 파일크기
	original_filename varchar(255) NOT NULL, -- 원본파일명
	stored_filename varchar(255) NOT NULL, -- 저장파일명
	uploaded_by varchar(100) NOT NULL, -- 업로드자ID
	qna_id int8 NOT NULL, -- 문의ID
	created_id varchar(100) NULL, -- 생성자ID
	updated_id varchar(100) NULL, -- 수정자ID
	updated_at timestamp(6) NOT NULL, -- 수정일시
	CONSTRAINT qna_attachments_pkey PRIMARY KEY (id),
	CONSTRAINT fk6po44275nmi0uo9y3sr1h0kim FOREIGN KEY (qna_id) REFERENCES public.qna(id)
);
