-- public.qna_attachments definition

-- Drop table

-- DROP TABLE public.qna_attachments;

CREATE TABLE public.qna_attachments (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	content_type varchar(100) NULL,
	created_at timestamp(6) NOT NULL,
	file_path varchar(500) NOT NULL,
	file_size int8 NOT NULL,
	original_filename varchar(255) NOT NULL,
	stored_filename varchar(255) NOT NULL,
	uploaded_by varchar(100) NOT NULL,
	qna_id int8 NOT NULL,
	created_id varchar(100) NULL,
	updated_id varchar(100) NULL,
	updated_at timestamp(6) NOT NULL,
	CONSTRAINT qna_attachments_pkey PRIMARY KEY (id),
	CONSTRAINT fk6po44275nmi0uo9y3sr1h0kim FOREIGN KEY (qna_id) REFERENCES public.qna(id)
);
