-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
	role_id varchar(20) NOT NULL,
	role_name varchar(100) NOT NULL,
	description varchar(500) NULL,
	use_yn varchar(1) DEFAULT 'Y'::bpchar NULL,
	created_id varchar(100) DEFAULT 'system'::character varying NULL,
	updated_id varchar(100) DEFAULT 'system'::character varying NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (role_id),
	CONSTRAINT roles_use_yn_check CHECK (((use_yn)::bpchar = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])))
);
