-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
	role_id varchar(20) NOT NULL, -- 역할ID
	role_name varchar(100) NOT NULL, -- 역할명
	description varchar(500) NULL, -- 설명
	use_yn varchar(1) DEFAULT 'Y'::bpchar NULL, -- 사용여부
	created_id varchar(100) DEFAULT 'system'::character varying NULL, -- 생성자ID
	updated_id varchar(100) DEFAULT 'system'::character varying NULL, -- 수정자ID
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL, -- 생성일시
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL, -- 수정일시
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (role_id),
	CONSTRAINT roles_use_yn_check CHECK (((use_yn)::bpchar = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])))
);
