-- 기존 attachments 테이블 삭제 후 재생성
-- 28.create_table_attchments.sql의 정확한 스키마로 재생성

-- 기존 테이블 삭제 (데이터도 함께 삭제됨)
DROP TABLE IF EXISTS public.attachments CASCADE;

-- 개선된 첨부파일 테이블
-- 여러 업무에서 공통으로 사용할 수 있도록 설계

CREATE TABLE public.attachments (
    attach_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    
    -- 파일 기본 정보
    original_name varchar(255) NOT NULL,     -- 원본 파일명 (originalName)
    stored_name varchar(255) NOT NULL,       -- 저장된 파일명 (fileName) 
    file_path varchar(500) NOT NULL,         -- 파일 저장 경로
    file_size int8 NOT NULL,                 -- 파일 크기 (bytes)
    mime_type varchar(100) NULL,             -- MIME 타입 (예: image/png, application/pdf)
    
    -- 업무별 구분을 위한 필드들
    entity_type varchar(50) NOT NULL,        -- 연결된 엔티티 타입 (예: 'rm_submit_mgmt' x테이블블)
    entity_id int8 NOT NULL,                 -- 해당 엔티티의 ID
    content_type varchar(100) NULL,          -- 콘텐츠 타입 (업무별 구분용, entity_type과 동일하게 사용 가능)
    
    -- 업로드 정보
    uploaded_by varchar(100) NOT NULL,       -- 업로드한 사용자 ID
    upload_date timestamp(6) NOT NULL DEFAULT now(), -- 업로드 시간 (uploadDate)
    
    -- 감사 정보
    created_id varchar(100) NULL,            -- 생성자 ID
    updated_id varchar(100) NULL,            -- 수정자 ID  
    created_at timestamp(6) NOT NULL DEFAULT now(), -- 생성 시간
    updated_at timestamp(6) NOT NULL DEFAULT now(), -- 수정 시간
    
    -- 논리적 삭제를 위한 필드 (선택사항)
    deleted_yn varchar(1) DEFAULT 'N' NULL,  -- 삭제 여부
    deleted_at timestamp(6) NULL,            -- 삭제 시간
    deleted_by varchar(100) NULL,            -- 삭제자 ID
    
    CONSTRAINT attachments_pkey PRIMARY KEY (attach_id)
);

-- 성능을 위한 인덱스
CREATE INDEX idx_attachments_entity ON public.attachments(entity_type, entity_id);
CREATE INDEX idx_attachments_upload_date ON public.attachments(upload_date);
CREATE INDEX idx_attachments_content_type ON public.attachments(content_type);

-- 삭제되지 않은 파일만 조회하는 인덱스 (논리적 삭제 사용 시)
CREATE INDEX idx_attachments_active ON public.attachments(entity_type, entity_id) WHERE deleted_yn = 'N';

COMMENT ON TABLE public.attachments IS '범용 첨부파일 관리 테이블';
COMMENT ON COLUMN public.attachments.entity_type IS '연결된 엔티티 타입 (예: LEDGER_MGMT_STRUCTURE_SUBMISSION, QNA, NOTICE 등)';
COMMENT ON COLUMN public.attachments.entity_id IS '해당 엔티티의 기본키 ID';
COMMENT ON COLUMN public.attachments.content_type IS '업무별 콘텐츠 구분 (entity_type과 동일하거나 더 세분화된 구분)';
COMMENT ON COLUMN public.attachments.mime_type IS '파일의 MIME 타입 (브라우저 다운로드 시 Content-Type 헤더 설정용)';