-- public.rm_submit_mgmt definition

-- Drop table

-- DROP TABLE public.rm_submit_mgmt CASCADE;

CREATE TABLE public.rm_submit_mgmt (
	rm_submit_mgmt_id bigserial NOT NULL,
	submit_hist_cd varchar(100) NOT NULL,
	execofficer_id int8 NOT NULL,
	rm_submit_dt date NULL,
	update_yn varchar(1) DEFAULT 'N'::character varying NULL,
	rm_submit_remarks varchar(1000) NULL,
	created_id varchar(100) NULL,
	updated_id varchar(100) NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	submit_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	attachment_file varchar(255) NOT NULL,
	executive_name varchar(255) NOT NULL,
	history_code varchar(255) NOT NULL,
	"position" varchar(255) NOT NULL,
	remarks varchar(255) NULL,
	submission_date date NOT NULL,
	CONSTRAINT rm_submit_mgmt_pkey PRIMARY KEY (rm_submit_mgmt_id)
);
