-- public."notice" definition

-- Drop table

-- DROP TABLE public."notice";

CREATE TABLE public."notice" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_id varchar(100) NULL,
	updated_at timestamp(6) NOT NULL,
	updated_id varchar(100) NULL,
	category varchar(50) NULL,
	title varchar(500) NOT NULL,
	"content" text NULL,
	pinned bool DEFAULT false NOT NULL,
	view_count int4 DEFAULT 0 NOT NULL,
	CONSTRAINT notice_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_notice_created_at ON public.notice USING btree (created_at);
CREATE INDEX idx_notice_pinned_created_at ON public.notice USING btree (pinned DESC, created_at DESC);