-- public.submitted_reports definition

-- Drop table

-- DROP TABLE public.submitted_reports;

CREATE TABLE public.submission_reports (
       SUBMISSION_REPORT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
       BASE_DATE DATE NOT NULL,
       TARGET_INSTITUTION VARCHAR(255) NOT NULL,

       -- 표준 감사(Audit) 컬럼
       use_yn BOOLEAN DEFAULT FALSE NOT NULL,
       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       created_by VARCHAR(100) ,
       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       updated_by VARCHAR(100) ,

       PRIMARY KEY (SUBMISSION_REPORT_ID)
);


